import { ThemeProvider } from "@/components/ThemeProvider"
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/AppSidebar"
import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from "@/components/AuthProvider"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
      >
        <AuthProvider>
        <SidebarProvider>
              <AppSidebar />
        <SidebarTrigger />
        {children}
        </SidebarProvider>
        </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
